name: Docs

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish docs
        run: cd docs && now --token $NOW_TOKEN --prod
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
