name: docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish docs
        run: cd docs && now --token $NOW_TOKEN --prod -c
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
